
trigger:
  branches:
    include:
      - main
      - 'develop'
      - 'release/*'
      - 'feature/*'
      - 'hotfix/*'
  tags:
    include:
      - 'v*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  fetchDepth: 2000
  persistCredentials: true
- script: |
    git fetch --tags
    ./cibuild.sh
- publish: $(System.DefaultWorkingDirectory)/artifacts
  artifact: Artifacts

